# NUMPY

### Searching array

In [1]:
a = np.array([1,2,3,4,5,6])

<IPython.core.display.Javascript object>

In [73]:
#searching for values
#Masking an array
a[a%2==0]

array([2, 4, 6])

In [6]:
#searching for index of value
np.where(a==4)

<IPython.core.display.Javascript object>

(array([3], dtype=int64),)

In [7]:
np.where(a%2==0)

<IPython.core.display.Javascript object>

(array([1, 3, 5], dtype=int64),)

In [1]:
x = np.array(['John','Peter','James','Peter'])

<IPython.core.display.Javascript object>

In [2]:
x[x=='James']

array(['James'], dtype='<U5')

In [78]:
np.where(x=='Satya')

(array([2, 4], dtype=int64),)

### Sorting

In [19]:
#Sorting array in ascending order
a = np.array([3,5,4,2])

<IPython.core.display.Javascript object>

In [16]:
np.sort(a)

<IPython.core.display.Javascript object>

array([2, 3, 4, 5])

In [3]:
x = np.array(['banana','apple','mango','orange','ant'])

<IPython.core.display.Javascript object>

In [4]:
np.sort(x)

<IPython.core.display.Javascript object>

array(['ant', 'apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [22]:
a = np.array([[3,1,2],[4,6,5]]) #2d array

<IPython.core.display.Javascript object>

In [23]:
np.sort(a)

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6]])

### Filtering

In [79]:
x = np.array([1,2,3,4,5,6])
arr = np.array([True,False,True,False,True,False])
x[arr]

array([1, 3, 5])

In [31]:
#Filtering odd numbers from an array
a =np.array([1,2,3,4,5,6,7,8,9])
arr =[]

for i in a :
    if i%2 == 0:
        arr.append(True)
    else:
        arr.append(False)
        
new_arr = a[arr]        
        
print(new_arr)        

<IPython.core.display.Javascript object>

[2 4 6 8]


In [32]:
[False,True,False,True,False,True,False,True,False]

<IPython.core.display.Javascript object>

4

In [ ]:
#Selecting random number from a particular set
np.random.choice([4,8,9,6,5,1,2,3])

In [35]:
np.random.choice([1,2,3],size=(3,4))

<IPython.core.display.Javascript object>

array([[1, 1, 2, 3],
       [2, 1, 3, 2],
       [2, 2, 1, 2]])

In [38]:
#Using probability while selecting random number
np.random.choice([4,6,8],p=[0.8,0.1,0.1],size=10)

<IPython.core.display.Javascript object>

array([6, 4, 4, 4, 8, 4, 8, 4, 4, 4])

In [40]:
np.random.choice([4,6,8],p=[0.8,0.1,0.1],size=(3,3))

<IPython.core.display.Javascript object>

array([[6, 6, 4],
       [4, 8, 8],
       [4, 4, 4]])

In [42]:
#Shuffling array
a = np.array([1,2,3,4,5,6])
np.random.shuffle(a)
print(a)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[4 5 1 3 6 2]


In [45]:
#Permutations
a = np.array([1,2,3,4,5])
np.random.permutation(a)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([3, 5, 2, 4, 1])

# PRACTICE

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6])

In [6]:
list_1 = [1,1.2,'a','apple']

In [10]:
list_1

[1, 1.2, 'a', 'apple']

In [13]:
a = np.array([1,1.2])

In [14]:
a

array([1. , 1.2])

In [15]:
a = np.array([[1,2],[3,4],[5,6]])

In [17]:
a = np.array([1,2,3,4,5,6], ndmin=2)

In [19]:
a.shape = (3,2)

In [21]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array([1,2,3],ndmin=3, dtype=complex)

In [26]:
a

array([[[1.+0.j, 2.+0.j, 3.+0.j]]])

In [27]:
a = np.array(['apple','ball','cat','dog','elephant'])

In [30]:
a[3]

'dog'

In [33]:
a[::2]

array(['apple', 'cat', 'elephant'], dtype='<U8')

In [34]:
a[1::2]

array(['ball', 'dog'], dtype='<U8')

In [35]:
arr1 = np.array([[1,2,3,4,5],[2,4,6,8,10],[3,6,9,12,15]])

In [36]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [39]:
arr1[1:,1:4]

array([[ 4,  6,  8],
       [ 6,  9, 12]])

In [41]:
arr1[1::2]

array([[ 2,  4,  6,  8, 10]])

In [42]:
arr1[arr1%2==0]

array([ 2,  4,  2,  4,  6,  8, 10,  6, 12])

In [55]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8]])

In [56]:
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8,9]])

In [61]:
a.shape

(3, 2)

In [67]:
arr1 = np.array([[1,2,3,4,5]])

In [68]:
arr1

array([[1, 2, 3, 4, 5]])

In [69]:
arr1[arr1%2==0]

array([2, 4])

In [70]:
np.where(arr1%2==0)

(array([0, 0], dtype=int64), array([1, 3], dtype=int64))

In [90]:
a = np.random.random(10)

In [91]:
a

array([0.6011255 , 0.17809151, 0.87036396, 0.42915573, 0.59473028,
       0.08612809, 0.61440254, 0.93581802, 0.07315787, 0.13475638])

In [93]:
x = np.random.randint(1,100,10)

In [94]:
x

array([ 7, 12, 15, 79, 33, 21, 96, 22, 97, 59])

In [95]:
np.sort(x)

array([ 7, 12, 15, 21, 22, 33, 59, 79, 96, 97])

In [102]:
a = np.array(['mango','ant','orange','banana','apple'])

In [103]:
np.sort(a)

array(['ant', 'apple', 'banana', 'mango', 'orange'], dtype='<U6')

True